### ISSUE TITLE
Using Cake.SemVer w/ Cake 1.1.0 produces warning

### ISSUE THREAD

**Issue by bradtwurst** [Redth/Cake.SemVer#17]
The assembly 'Cake.SemVer, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.33.0).  For best compatibility it should target Cake.Core version 1.0.0.

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem
